### ISSUE TITLE
The CSS doesn't show up with github pages

### ISSUE THREAD

**Issue by anhskrttt** [srid/emanote-template#62]
I created a new repo with this template (include all branches). I didn't change anything, just keep everything the same, but when I visited [my cloned repo's github site](https://anhskrttt.github.io/test/), the page only showed html content **without the css**. 

Despite this, everything run smoothly on local environment when I cloned my repo to and run command `emanote run --port=8080`. Both html and css worked as expected (but only locally)!

Can anyone suggest me how to fix this? Again, pls notice that I just simply cloned the whole projects without any further actions. Is there anything else I must config to make my github page "shows its css"?

Thanks for your help!

**Comment by srid** [comment]
Did you follow the instructions around `baseUrl` in the README?

https://github.com/srid/emanote-template#using-this-template

<img width="661" alt="image" src="https://github.com/srid/emanote-template/assets/3998/f79c9922-cbdb-41de-8342-abcf9caaaecd">

**Comment by anhskrttt** [comment]
> Did you follow the instructions around `baseUrl` in the README?
> 
> https://github.com/srid/emanote-template#using-this-template
> 
> <img alt="image" width="661" src="https://user-images.githubusercontent.com/3998/274940247-f79c9922-cbdb-41de-8342-abcf9caaaecd.png">


It works like a charm now!!! Thanks!
